apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coroot
  namespace: argo  # Namespace onde o Argo CD está instalado
spec:
  project: default
  source:
    repoURL: https://coroot.github.io/helm-charts
    chart: coroot
    targetRevision: 0.15.15
    helm:
      valueFiles: []
      values: |
        corootCE:
          enabled: true
          bootstrap:
            clickhouse:
              database: default
              username: default
              password: admin@123
          ingress:
            enabled: false
            className: nginx
            hostname: coroot.local
          persistentVolume:
            size: 5Gi
          service:
            type: NodePort
            nodePort: 30180
        prometheus:
          server:
            persistentVolume:
              size: 5Gi
        clickhouse:
          enabled: true
          auth:
            username: default
            password: admin@123
          persistence:
            size: 10Gi
        node-agent:
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: coroot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
