apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-k8s-math
  namespace: argo
spec:
  project: default
  source:
    repoURL: http://chartmuseum.chartmuseum:8080
    chart: dotnet-k8s-math-chart
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dotnet-k8s-math
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
