apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo
  namespace: argo  # Namespace do Argo CD
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.21.0
    helm:
      values: |
        # Aqui você pode adicionar valores personalizados, se necessário
        # Exemplo:
        # traces:
        #   otlp:
        #     grpc:
        #       enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
