apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo
spec:
  project: default

  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.0
    helm:
      releaseName: harbor
      values: |
        expose:
          type: nodePort
          nodePort:
            name: harbor
            ports:
              http:
                port: 80
                nodePort: 30002
              https:
                port: 443
                nodePort: 30003

        externalURL: https://10.7.53.154:30003

        harborAdminPassword: "cauan@123"

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

