apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://netdata.github.io/helmchart
    chart: netdata
    targetRevision: 3.7.130
    helm:
      values: |
        image:
          tag: edge
        service:
          type: NodePort
        ingress:
          enabled: false
        parent:
          claiming:
            enabled: true
            token: "0AXzruHhF1h1H8mAU2750ihoS1AZnxx2FFpdVkVEQPpckS_NLiEZqVMQhKx-a3QAW2f_4DWHQiiob3fBBaPhdGmEyBVghyoMPmCdKMy1mihs7cbEQN_hIWsbQbgAsWg3WjFP8b8"
            rooms: "2ab6b4c7-024e-47cf-9816-65028cc62258"
        child:
          claiming:
            enabled: true
            token: "0AXzruHhF1h1H8mAU2750ihoS1AZnxx2FFpdVkVEQPpckS_NLiEZqVMQhKx-a3QAW2f_4DWHQiiob3fBBaPhdGmEyBVghyoMPmCdKMy1mihs7cbEQN_hIWsbQbgAsWg3WjFP8b8"
            rooms: "2ab6b4c7-024e-47cf-9816-65028cc62258"
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
