apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo  # Namespace onde o Argo CD está instalado
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.8.0
    helm:
      values: |
        extraScrapeConfigs: |
          - job_name: 'otel-collector'
            static_configs:
              - targets: ['opentelemetry-collector.opentelemetry:8889']
        server:
          persistentVolume:
            enabled: false
            size: 10Gi
          service:
            type: NodePort
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
        ingress:
          enabled: false
          ingressClassName: nginx
          annotations: {}
          labels: {}
          path: /
          pathType: Prefix
          hosts:
            - prometheus.local
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
