apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo  # Namespace correto onde o Argo CD está instalado
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.1
    helm:
      valueFiles: []
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
