apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-k8s-math
  labels:
    app: dotnet-k8s-math
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-k8s-math
  template:
    metadata:
      labels:
        app: dotnet-k8s-math
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: 'opentelemetry/instrumentation'
    spec:
      containers:
      - name: dotnet-k8s-math-container
        image: cauanlima/dotnet-k8s-math:v1.0.6
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: dotnet-k8s-math
spec:
  selector:
    app: dotnet-k8s-math
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31002

